### ISSUE TITLE
Matlab CPUs\GPU ?

### ISSUE THREAD

**Issue by mladendalto** [foges/pogs#22]
How do I ensure GPU optimization in Matlab ?
I checked pogs help under Matlab and went trough code quickly, but no luck.
Is there a way to tell it use CPUs\GPU, or it just happens in the background ?

**Comment by foges** [comment]
Hi Mladendalto,

When you run `pogs_setup` you should see that the it build the GPU version (https://github.com/foges/pogs/blob/master/src/interface_matlab/pogs_setup.m#L46). Also, if you check out the `cone` branch (which will be merged into the master branch soon), you'll see that either CPU or GPU is printed when you run pogs (https://github.com/foges/pogs/blob/cone/src/gpu/pogs.cu#L197)
