### ISSUE TITLE
Clearify license

### ISSUE THREAD

**Issue by tosttost** [foges/pogs#23]
Can you please clarify the license of POGS? I neither found a COPYING file nor a license/copyright header at the top of a source file.

http://foges.github.io/pogs/ says GPL.
Paper and src/interface_r/pogs/DESCRIPTION say 3-Clause-BSD.

BSD is great. GPL would be quite limiting.

**Comment by foges** [comment]
Sorry for the confusion. When I started I used the GPL license, but as I realized the limitations, I changed it to a BSD-3 license. I'll update the github.io website to reflect the changes, but in the mean-time, yes it's BSD-3 licensed.

**Comment by tosttost** [comment]
Great! I have a real world problem with linear constraints, entropy + linear terms in the objective and modest requirements for accuracy. So I'll try POGS - based on the paper it looks very promising :)

Meanwhile I found the "Gnu Scientific Library" comment in src/cpu/include/gsl/gsl_blas.h

Hopefully you didn't pasted code from GSL? AFAIK the GSL is written in plain old C, but the code in that file is definitely C++.
As the GSL is distributed under the GPL relicensing under BSD would be difficult.

**Comment by foges** [comment]
Glad to hear :) I'd be interested in knowing how it works out for you (btw, the code in the `cone` branch is a fair bit newer, and also supports specifying the problem in cone form).

When I started out I used the Gnu Scientific Library, however at some point I realized that I only needed a very small subset of the functionality, and that I wanted more freedom (eg. adding template parameters for float vs. double), so I kept the basic API, but re-wrote the implementation myself. As a result, there is no re-licensing issue. All the code is distributed with a BSD license.

**Comment by tosttost** [comment]
We experienced severe problems (max iterations exceeded or no convergence at all) if there are linear dependent rows inside the matrix A. We use cpu + sparse matrix + indirect solver + linear objective. Is there a simple workaround apart from remodelling the whole problem?

If this behaviour is 'by design', a warning in the docs would be great :)

**Comment by ledell** [comment]
FYI, the [POGS website](https://foges.github.io/pogs/) still references the GPL license.  It says "POGS is written in C++ and is fully open source (GPL)."  I would submit a PR to make the change to BSD-3 directly, but I can't find the repo where the docs are hosted.

**Comment by foges** [comment]
Thanks for spotting the discrepancy. I've updated the license on the github pages and also added a section to the README.md. For future reference all the github pages sources are on the gh-pages branch.
