### ISSUE TITLE
MATLAB version will not compile

### ISSUE THREAD

**Issue by harel-primack** [foges/pogs#26]
Hi,

I tried to compile PGOS on MATLAB with no success.

Any help?

Win 10
MATLAB 2017b
MinGW64 Compiler

Error message:

>> pogs_setup
'make' is not recognized as an internal or external command, 
operable program or batch file. 
'make' is not recognized as an internal or external command, 
operable program or batch file. 

Error using mex
MEX cannot find library 'mwblas' specified with the -l option.
 MEX looks for a file with one of the names:
 libmwblas.lib
 mwblas.lib
 Please specify the path to this library with the -L option.

Error in pogs_setup (line 33)
  eval(sprintf(['mex -largeArrayDims -I../include ' ...

**Comment by adil3480** [comment]
I have same issue.

**Comment by XinchenDengll** [comment]
Hi, friend.
Have you figured out this problem? I have the same problem.

**Comment by foges** [comment]
Hi @harel-primack @adil3480 @XinchenDengll -- I'm sure all of you have long moved on, but nonetheless in response. I currently don't support Windows, but would love any contributions adding support.
