### ISSUE TITLE
Missing memory movement in the C interface

### ISSUE THREAD

**Issue by tygert** [foges/pogs#27]
The three lines with memcpy omit "sizeof(T)"....

(1) The final argument, "n", wants to be "n * sizeof(T)":
https://github.com/foges/pogs/blob/81e3d89f0db399de56f5ba9d8302010632847bfe/src/interface_c/pogs_c.cpp#L48

(2) The final argument, "m", wants to be "m * sizeof(T)":
https://github.com/foges/pogs/blob/81e3d89f0db399de56f5ba9d8302010632847bfe/src/interface_c/pogs_c.cpp#L49

(3) The final argument, "m", wants to be "m * sizeof(T)":
https://github.com/foges/pogs/blob/81e3d89f0db399de56f5ba9d8302010632847bfe/src/interface_c/pogs_c.cpp#L50

**Comment by foges** [comment]
Thank you for finding that @tygert. That's definitely an issue. I've fixed it now.
