### ISSUE TITLE
Iterative pogs memory leak in MATLAB 2018

### ISSUE THREAD

**Issue by CPLambert** [foges/pogs#29]
This is a really great method! However, I have embedded pogs in a loop that iterates many many times and there is a memory leak resulting in an inevitable crash. Any ideas/suggestions? I'm assuming somewhere an array needs destroying.

Thanks

**Comment by CPLambert** [comment]
Ah, may be worth mentioning I'm running this on Centos7.

**Comment by eloi-loomai** [comment]
Same problem on my end, ran valgrind on it, the leak is here:
matrix_dense.cpp +83
```
  // Copy Matrix to GPU.
  _data = new T[this->_m * this->_n];
```

Please Pogs project team, fix this :)

**Comment by foges** [comment]
This response is way overdue. Thanks for reporting that @CPLambert and for figuring out the issue @eloi-loomai. Definitely a bit embarrassing to forget to delete the data from a matrix class. I've pushed a fix.

@bungun thanks for the notes on fixes. I'll try and diff to see what else might be missing.
