### ISSUE TITLE
posg_setup not working on Matlab 

### ISSUE THREAD

**Issue by adil3480** [foges/pogs#30]
I tried to run pogs_setup on Matlab, but it gives  a series of errors. 

'make' is not recognized as an internal or external command, 
operable program or batch file. 
'make' is not recognized as an internal or external command, 
operable program or batch file. 
Building with 'Microsoft Visual C++ 2015'.
Error using mex
pogs_mex.cpp

I am running it on Matlab R2018a and CUDA 9.0 is installed on my machine.

**Comment by foges** [comment]
Hi @adil3480. Pogs currently doesn't support Windows. I don't have a windows PC, but I'd love it if you'd contribute changes.
