### ISSUE TITLE
Path include error on ubuntu/debian R installation + fix

### ISSUE THREAD

**Issue by apoorvalal** [foges/pogs#33]
I was getting a `R.h not found` error when installing according to the docs, and did some digging about where it was looking for `R.h`. `interface_r/pogs/src/config.mk` defines `R_INC:=$(R_HOME)/include`, but the debian install of R stores these files in `/usr/share/R/include`. Commenting out [Line 7 in config.mk](https://github.com/foges/pogs/blob/master/src/interface_r/pogs/src/config.mk#L7) and installing from the package directory using `devtools::install` worked.

**Comment by foges** [comment]
Thanks Apoorval. Thanks for raising this. I would have hoped that RHOME takes care of this, but I guess not. I'll add both of the includes to cover both cases.
